### ISSUE TITLE
How to correct this sample

### ISSUE THREAD

**Issue by ghost** [tkowalczyk/CustomBindablePicker#1]
Please see the two images for the required changes to your code.

This Bindable picker works just like Windows Forms or WPF ComboBox's do.

Please read up on using SelectedItem and SelectedValue, they operate differently.  These images show how to use the control as intended.

Best regards,

karl

![reply1](https://cloud.githubusercontent.com/assets/5623887/16726362/c0755e5e-4729-11e6-86f4-0ffaa0031ae7.png)
![reply2](https://cloud.githubusercontent.com/assets/5623887/16726361/c0748a6a-4729-11e6-9aac-f37aeb9968e9.png)

**Comment by tkowalczyk** [comment]
Hi big thanks, but I still can't see the `Abbreviation` except the `Value` in the first picker.

**Comment by ghost** [comment]
The **DisplayMemberPath** is **Value**, Value is what is being displayed in the picker.

I don't understand what the problem is.  It's working according to the properties in XAML.

What do you expect to show?

**Comment by tkowalczyk** [comment]
Yes of course it is working now. My mistake. Thank you Karl!
